# SPDX-FileCopyrightText: 2026 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0

name: Checks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-openapi:
    name: build:openapi
    runs-on: ubuntu-latest
    container:
      image: node:24-alpine
    steps:
      - uses: actions/checkout@v7

      - name: Lint OpenAPI spec
        run: npx -y @redocly/cli lint --config doc/redocly.yaml doc/openapi/openapi.yaml

      - name: Build OpenAPI docs
        run: npx -y @redocly/cli build-docs --config doc/redocly.yaml doc/openapi/openapi.yaml --output openapi.html

      - uses: actions/upload-artifact@v7
        with:
          name: openapi
          path: openapi.html

  pre-commit:
    name: test:pre-commit
    runs-on: ubuntu-latest
    container:
      image: python:3.12.10-slim-bookworm
      options: --user root
    steps:
      - name: Install git and ruby
        run: apt-get update && apt-get -y install git ruby

      - uses: actions/checkout@v7

      - name: Add Git safe directory
        run: git config --global --add safe.directory '*'

      - name: Install pre-commit
        run: pip install --no-cache-dir pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Upload log
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: pre-commit-log
          path: /github/home/.cache/pre-commit/pre-commit.log

  reuse:
    name: test:reuse
    runs-on: ubuntu-latest
    container:
      image: fsfe/reuse:latest
      options: --entrypoint ""
    steps:
      - uses: actions/checkout@v7

      - name: Run REUSE lint
        run: reuse lint
