# SPDX-FileCopyrightText: 2014-2023 Institute for Automation of Complex Power Systems, RWTH Aachen University
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      docker_image: ${{ steps.image.outputs.docker_image }}
    steps:
      - name: Compute image name for the current repository
        id: image
        env:
          OWNER: ${{ github.repository_owner }}
        run: echo "docker_image=ghcr.io/${OWNER,,}/villas/node" >> "$GITHUB_OUTPUT"

  checks:
    uses: ./.github/workflows/checks.yml
    secrets: inherit

  prepare:
    needs: [setup]
    uses: ./.github/workflows/prepare.yml
    with:
      docker_image: ${{ needs.setup.outputs.docker_image }}
    secrets: inherit

  build:
    needs: [setup, prepare]
    uses: ./.github/workflows/build.yml
    with:
      docker_image: ${{ needs.setup.outputs.docker_image }}
    secrets: inherit

  test:
    needs: [setup, build]
    uses: ./.github/workflows/test.yml
    with:
      docker_image: ${{ needs.setup.outputs.docker_image }}
    secrets: inherit

  packaging:
    if: github.event_name != 'pull_request'
    needs: [setup, test]
    uses: ./.github/workflows/packaging.yml
    with:
      docker_image: ${{ needs.setup.outputs.docker_image }}
    secrets: inherit

  deploy:
    if: github.event_name != 'pull_request'
    needs: [setup, packaging]
    uses: ./.github/workflows/deploy.yml
    with:
      docker_image: ${{ needs.setup.outputs.docker_image }}
    secrets: inherit
